# Generated by Django 5.1.7 on 2025-03-26 05:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("Home", "Home"),
                    ("Work", "Work"),
                    ("Rental", "Rental"),
                    ("Other", "Other"),
                ],
                default="Home",
                max_length=10,
                verbose_name="address type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/mohantejadharmavarapu/Projects/Real Estate/backend/media/profile_pictures"
                ),
                upload_to="",
                verbose_name="profile_image",
            ),
        ),
    ]
