# Generated by Django 5.1.7 on 2025-03-30 16:04

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/mohantejadharmavarapu/Projects/Sai Events/backend/media/profile_pictures'), upload_to='', verbose_name='event_image')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.TextField(choices=[('On Site', 'Onsite'), ('Hybrid', 'Hybrid'), ('Online', 'Online')])),
                ('date', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
